name: Hand-on CI-CD Pipeline
on: [push]

jobs:
  Build-Stage:
    runs-on: ci-worker
    steps:
      - name: Disable SSL and Fix Git
        run: |
          git config --global http.sslVerify false
          git config --global http.postBuffer 524288000 # 增加緩衝區，預防大檔案失敗

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # 停用預設的 Token 認證，改用簡單模式
          persist-credentials: false 

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .